const colors = require("tailwindcss/colors");
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    colors: {
      primary: {
        50: "#F5E1F7",
        100: "#ECBDF2",
        200: "#CE80D9",
        300: "#BB61C7",
        400: "#AD4BB8",
        500: "#A23DAD",
        600: "#90279C",
        700: "#7C1A87",
        800: "#671270",
        900: "#4E0754",
      },
      secondary: {
        50: "#FFE8D9",
        100: "#FFD0B5",
        200: "#FFB088",
        300: "#FF9466",
        400: "#F9703E",
        500: "#F35627",
        600: "#DE3A11",
        700: "#C52707",
        800: "#AD1D07",
        900: "#841003",
      },
      neutral: colors.gray,
      black: colors.black,
      white: colors.white,
      transparent: "transparent",
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      lime: colors.lime,
      green: colors.green,
      teal: colors.teal,
      sky: colors.sky,
      indigo: colors.indigo,
      violet: colors.violet,
      fuchsia: colors.fuchsia,
      rose: colors.rose,
      yellow: colors.yellow,
    },
    borderColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: theme("colors.neutral.200", "currentColor"),
    }),
    backgroundColor: (theme) => ({
      ...theme("colors"),
    }),
    extend: {},
  },
  plugins: [],
 };